org: connectrix
app: connectrix-DB

service: db-server

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1

functions:
  api:
    handler: dist/lambda.handler
    events:
      - httpApi: '*'
