name: CI/CD Pipeline

# Triggers
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  # CI Job
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn' # Changed from npm to yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile # Changed from npm ci

      #   - name: Lint check
      #     run: yarn lint

      #   - name: Type check
      #     run: yarn type-check

      #   - name: Run tests
      #     run: yarn test

      - name: Build
        run: yarn build

  # CD Jobs
  deploy-production:
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to production
        run: yarn deploy
        env:
          STAGE: production
